### ISSUE TITLE
clear approach for validation/indexing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#156]
@s3mi0 & @vyacheslav.chub  the idea with a ddf prefix is to exclude other files from validation. @jasper

Jasper Heeffer [12:19 AM]  
ah, good one @olarosling, so @vyacheslav.chub 
if ddf-index: validate only what is in index
if no ddf-index: validate only with `ddf--` prefix

https://gapminder.slack.com/archives/on_datasets/p1467235118000127

**Comment by jheeffer** [comment]
Isn't this already the way it works? If there's an index validator checks only files pointed at in the index. If there is none, validator checks only files with valid ddf filename? 

How does validator choose what files to validate now?
