### ISSUE TITLE
New rule: capital_booleans

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ddf-validation#206]
* **Rule name:** 
capital_booleans

* **Rule description:** 
The boolean values in data should be all-upper or all-lower case 

* **Examples of correct data:**
`true`, `TRUE`

* **Examples of incorrect data:**
`True`, `1`, `"1"`

**Comment by buchslava** [comment]
@angieskazka what about '0' and '1' values. Are they incorrect?

**Comment by angieskazka** [comment]
@buchslava i just tried it with DDFCSV reader: judging from what it does, 1 and 0 should be invalid =)

**Comment by buchslava** [comment]
@angieskazka fixed, use version `0.12.10`
