### ISSUE TITLE
INVALID_CONCEPT_IN_DATAPOINT rule implementation

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#224]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

INVALID_CONCEPT_IN_DATAPOINT

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

string concept is present in a datapoint (header), for example

should be Error type and WAFFLE_SERVER tag

* **Examples of correct data:**

* **Examples of incorrect data:**

* **Scenarios** Should be filled if type of Request is `rule`.

**Comment by jheeffer** [comment]
Oh, so WAFFLE_SERVER tag means that this invalidity is specifically for waffle server support?

**Comment by buchslava** [comment]
@jheeffer yes, excatly
