### ISSUE TITLE
Datapoint key-duplicates are not found

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/ddf-validation#238]
1. Take https://github.com/open-numbers/ddf--gapminder--systema_globalis 
2. Check it's valid (it should be)
3. Add a datapoint, entity and concept with duplicate key (e.g. alb 1997 3 in `ddf--datapoints--20120905_extreme_poverty_percent_people_below_125_a_day--by--geo--time.csv`)
4. run validator
5. See only issues for concept and entity ids not being unique.

Expected result:

The added datapoint key (alb 1997) should be found as non-unique.

General rule: In one file, keys should be unique. This should be the case for datapoints, entities and concepts alike.

**Comment by buchslava** [comment]
DUPLICATED_DATA_POINT_KEY rule
