### ISSUE TITLE
UNEXPECTED_TRANSLATIONS_DATA rule implementation

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#247]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

UNEXPECTED_TRANSLATIONS_HEADER
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/unresolved-translations`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

Non consistent (empty) data in primary-key fields.
- **Examples of correct data:**

ddf--translation--en-us--datapoints--gov_type--by--geo--year.csv
and
ddf--datapoints--gov_type--by--geo--year.csv
- **Examples of incorrect data:**

ddf--translation--en-us--datapoints--gov_type--by--geo--foo.csv
and
ddf--datapoints--gov_type--by--geo--year.csv
- Notes

This rule should be applied only for indexless dataset.

**Comment by jheeffer** [comment]
This rule is also for indexed dataset! Any dataset.
