### ISSUE TITLE
UNEXPECTED_TRANSLATIONS_HEADER rule implementation

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#248]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

UNEXPECTED_TRANSLATIONS_HEADER
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/unexpected-translations-header`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired for 2 cases:
1. Translations header contains unexpected concepts: concepts that not present in related data (entities, datapoints).
2. Required headers should be present. Required headers can be: entities (set/domain) and time or entities (set/domain).
- **Examples of correct data:**

`ddf--datapoints--government_type--name--population--by--country--year.csv`

```
country,year,government_type,name,population
ger,1940,dictatorship,German Empire,8584
ger,2015,parliamentary democracy,Federal Republic of Germany,9293
swe,2015,parliamentary democracy,Kingdom of Sweden,2874
ned,2015,parliamentary democracy,Kingdom of the Netherlands,3374
```

`ddf--translation--de--datapoints--government_type--population--name--by--country--year.csv`

```
country,year,name
ger,1940,Deutsches Reich
swe,2015,Königreich Schweden
```
- **Examples of incorrect data:**

Case 1:

`ddf--datapoints--government_type--name--population--by--country--year.csv`

```
country,year,government_type,name,population
ger,1940,dictatorship,German Empire,8584
ger,2015,parliamentary democracy,Federal Republic of Germany,9293
swe,2015,parliamentary democracy,Kingdom of Sweden,2874
ned,2015,parliamentary democracy,Kingdom of the Netherlands,3374
```

`ddf--translation--de--datapoints--government_type--population--name--by--country--year.csv`

```
country,year,name,foo
ger,1940,Deutsches Reich,bar
swe,2015,Königreich Schweden,baz
```

Case 2:

`ddf--datapoints--government_type--name--population--by--country--year.csv`

```
country,year,government_type,name,population
ger,1940,dictatorship,German Empire,8584
ger,2015,parliamentary democracy,Federal Republic of Germany,9293
swe,2015,parliamentary democracy,Kingdom of Sweden,2874
ned,2015,parliamentary democracy,Kingdom of the Netherlands,3374
```

`ddf--translation--de--datapoints--government_type--population--name--by--country--year.csv`

```
country,name
ger,Deutsches Reich
swe,Königreich Schweden
```
- Notes

This rule should be applied only for indexless dataset.

**Comment by jheeffer** [comment]
Also for indexed datasets :)!
