### ISSUE TITLE
DUPLICATED_TRANSLATION_KEY rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#252]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

DUPLICATED_TRANSLATION

- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/duplicated-translation`

- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when same translation key was found more than once

- **Examples of correct data:**

`ddf--datapoints--government_type--name--population--by--country--year.csv`

```
country,year,government_type,name,population
ger,1940,dictatorship,German Empire,8584
ger,2015,parliamentary democracy,Federal Republic of Germany,9293
swe,2015,parliamentary democracy,Kingdom of Sweden,2874
ned,2015,parliamentary democracy,Kingdom of the Netherlands,3374
```

`ddf--translation--de--datapoints--government_type--population--name--by--country--year.csv`

```
country,year,name
ger,1940,Deutsches Reich
swe,2015,Königreich Schweden
```
- **Examples of incorrect data:**

`ddf--datapoints--government_type--name--population--by--country--year.csv`

```
country,year,government_type,name,population
ger,1940,dictatorship,German Empire,8584
ger,2015,parliamentary democracy,Federal Republic of Germany,9293
swe,2015,parliamentary democracy,Kingdom of Sweden,2874
ned,2015,parliamentary democracy,Kingdom of the Netherlands,3374
```

`ddf--translation--de--datapoints--government_type--population--name--by--country--year.csv`

```
country,year,name
ger,1940,Deutsches Reich
ger,1940,Deutsches Reich1
swe,2015,Königreich Schweden
```

- Notes

This rule should be applied only for indexless dataset.

**Comment by jheeffer** [comment]
Not only for indexless, any dataset.
