### ISSUE TITLE
﻿⁠⁠⁠⁠nested folder supporting﻿⁠⁠ for ﻿⁠⁠⁠⁠datapackage

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#260]
﻿⁠⁠⁠⁠nested folder supporting﻿⁠⁠⁠⁠ fetaure for ﻿⁠⁠⁠⁠datapackage creation﻿⁠⁠⁠⁠ functionality in ﻿⁠⁠⁠⁠ddf-validation

**Comment by buchslava** [comment]
@jheeffer is this issue still actual?

**Comment by buchslava** [comment]
I guess this feature is expected for `--multidir` mode

**Comment by jheeffer** [comment]
This is for both datapackage creation and dataset validation. It's not --multidir. It's about data files of one dataset being in a different directory than root.
