### ISSUE TITLE
DATAPOINT_WITH_EMPTY_INDICATOR and DATAPOINT_WITHOUT_INDICATOR rules i

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#284]

**Comment by jheeffer** [comment]
Can you give an example of these?

**Comment by buchslava** [comment]
DATAPOINT_WITH_EMPTY_INDICATOR:

`ddf--datapoints--gas_production_bcf--by--geo--year.csv`
```
geo,year,gas_production_bcf
algeria,1970,0.24510633312511
algeria,1971,
```

DATAPOINT_WITHOUT_INDICATOR:
`datapackage.json`
```
..................
	"resources": [
		{
			"path": "ddf--concepts.csv",
			"name": "ddf--concepts",
			"schema": {
				"fields": [
					{
						"name": "concept"
					},
					{
						"name": "concept_type"
					},
					{
						"name": "name"
					}
				],
				"primaryKey": "concept"
			}
		},
		{
			"path": "ddf--datapoints--foo--by--geo--year.csv",
			"name": "ddf--datapoints--foo--by--geo--year",
			"schema": {
				"fields": [
					{
						"name": "geo"
					},
					{
						"name": "year"
					}
				],
				"primaryKey": [
					"geo",
					"year"
				]
			}
		},
.............
```

**Comment by jheeffer** [comment]
A datapoint with empty indicator is fine. It represents null i.e. no data available. It's not invalid.
Is it a problem for Waffle Server or DDFcsv reader @rychkog ?

**Comment by buchslava** [comment]
@jheeffer 
@rychkog said that empty indicator is a problem for WS. I think it's not a problem for DDFcsv reader

**Comment by jheeffer** [comment]
Result of discussion:

`DATAPOINT_WITH_EMPTY_INDICATOR` is valid, no validation rule needed for this case
`DATAPOINT_WITHOUT_INDICATOR` is invalid, validation rule needed for this case
