### ISSUE TITLE
incorrect entity recognition during datapackage creation

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#363]
{ id: 'DATAPACKAGE_NON_CONCEPT_PRIMARY_KEY',
  type: 'Non concept primary key in datapackage.json',
  path: '/home/vs/.ws-importer-cli/repos/VS-work/ddf--gapminder--systema_globalis--light/master/ddf--datapoints--sg_gdp_p_cap_const_ppp2011_dollar--by--geo-usa-swe--time.csv',
  data: { nonConcepts: [ `'geo-usa-swe'` ] } }
{ id: 'NON_UNIQUE_ENTITY_VALUE',
  type: 'Non unique entity value.\n  An issue according to this rule will be fired when id value entity \n  (under particular kind of entity, geo-country, for example) is not unique.',
  path: '/home/vs/.ws-importer-cli/repos/VS-work/ddf--gapminder--systema_globalis--light/master/ddf--entities--geo--geographic_regions.csv',
  data: 
.........................

it should be `geo` instead `geo-usa-swe`

**Comment by buchslava** [comment]
@korel-san what version of ddf-validation are you using? current is 1.4.1.

**Comment by buchslava** [comment]
@rychkog look please at the rest of the errors for 'ddf--gapminder--systema_globalis--light'. Is validator right in this case?

**Comment by rychkog** [comment]
It is not used - this dataset is obsolete
