### ISSUE TITLE
primaryKey and fields in datapackage does not corresponds with a header in csv file

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#376]
new rule
----------------------------
for example,
primaryKey for
`ddf--datapoints--broadband_subscribers_per_100_people--by--geo--time.csv`
is
```
                "primaryKey": [
                    "geo",
                    "time"
                ]
```

but the first line of the file is:

`geo,foo,broadband_subscribers_per_100_people`

when `foo` is a valid concept described on datapackage and concepts.csv

**Comment by jheeffer** [comment]
Filenames can be anything at validation. Only at datapackage.json creation they are used (and may cause problems).

**Comment by buchslava** [comment]
I found next rules related to this issue:

DATAPACKAGE_CONFUSED_FIELDS - this rule does not check kind of field
DATAPACKAGE_NON_CONCEPT_PRIMARY_KEY - this rule checks only primaryKey, not field

But both of these rules does not resolve `fields consistency problem`.  I think I can solve this problem easy:

1. DATAPACKAGE_NON_CONCEPT_PRIMARY_KEY should be DATAPACKAGE_NON_CONCEPT_FIELD
2. add to DATAPACKAGE_CONFUSED_FIELDS next case: check if fields contains primaryKey

**Comment by jheeffer** [comment]
As discussed on slack:

`DATAPACKAGE_NON_CONCEPT_FIELD` is indeed needed

`DATAPACKAGE_CONFUSED_FIELDS` might already be checked by datapackage-js validation. Would be interesting to look into that.
