### ISSUE TITLE
prevent to keep all of datapoints at the same data structure during ddfSchema creation

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#386]

**Comment by jheeffer** [comment]
@vyacheslav.chub `no need to read all of datapoints during ddfSchema creation` sounds scary

[11:58] 
please be specific. You do definitely need to read all datapoints for ddfSchema creation (edited)

[11:59] 
but you don't need to keep them all in memory at once (edited)

[11:59] 
it can be done streaming, I think (edited)

Jasper Heeffer [12:08 PM] 
Do you understand what I mean?

Slava Chub [12:22 PM] 
@jasper yes agreed, maybe this one `prevent to keep all of datapoints at the same data structure during ddfSchema creation` is better

regarding streaming: I have simple and not simple approaches to solve this issue:

1. synchronous reading (maybe this functionality will be slower)
2. streams using, but I suppose, it's a hard way; great refactoring is expected (synchronous to asynchronous functionality transformation) (edited)

Jasper Heeffer [12:39 PM] 
well, let's first get memory usage down, whatever way you think is easiest
