### ISSUE TITLE
indicator missing in datapackage.json

### ISSUE THREAD

**Issue by semio** [Gapminder/ddf-validation#449]
dataset: https://github.com/harpalshergill/ddf--unpop--wpp_population
ddf-validation: 1.8.0

there is an indicator `ddf--datapoints--dependencyratio1564--by--country--year--variant`: https://github.com/harpalshergill/ddf--unpop--wpp_population/tree/master/ddf--datapoints--dependencyratio1564--by--country--year--variant

But this indicator is not in datapackage.json, which is generated by ddf-validation. Not sure if there are more missing indicators. Please check.

**Comment by buchslava** [comment]
@semio Are you sure that latest version (1.8.0) was used or `datapackage.json` was recreated after repository's changing? I just created `datapackage.json` via 1.8.0 and:

![screenshot from 2017-07-24 15-03-21](https://user-images.githubusercontent.com/6974213/28522952-dbcc22ea-7082-11e7-8235-6c301b4fd208.png)

![screenshot from 2017-07-24 15-02-42](https://user-images.githubusercontent.com/6974213/28522953-dfa99dfc-7082-11e7-8c9d-bc54bec123c0.png)

**Comment by semio** [comment]
oh, sorry I didn't confirm with Harpal. So possibly Harpal is using an old version.

**Comment by buchslava** [comment]
@semio ok, cool, please close the issue when you will be ready

**Comment by semio** [comment]
ok, close
