### ISSUE TITLE
Validate concept types: only allow those allowed on WS

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ddf-validation#466]
According to specification we have next valid types for concepts:  'entity_domain', 'entity_set', 'time', 'string', 'measure'. I've found that for `tag` concept [was used](https://github.com/open-numbers/ddf--gapminder--systema_globalis/blob/7aa65c2a2c4686e49a2faf93bb22dd35cd3a338e/ddf--concepts.csv#L538) type `tag` instead of `entity_domain` which isn't in specification. Is it possible to change this type to the valid one?

so here we go, if there is something that is limiting WS from accepting dataset it should be in validator. so validator should be able to tell it to me, not you after manual investigation

**Comment by buchslava** [comment]
@angieskazka tell me please what changes should I apply on validator? It seems like this issue is not related to validator. Am I right?
