### ISSUE TITLE
Can entity property and entity key be same concept?

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/ddf-validation#472]
Is it invalid for a dataset to contain a key-value pair where the key and value are the same?
In other words, can you have a `geo` entity with property `geo`. Or a `country` entity with property `country` like `sgp` below. 

| geo | name           | country | is--country | is--city |
| ------------- | ------------- | ----- | ---- | --- |
| swe     | Sweden | | true | false |
| sgp | Singapore | sgp | true | true |
| sto      | Stockholm      | swe | false | true |

One way to easily spot it is existence of key-value pairs in ddfSchema with key and value same concept like these:
```
            {
                "primaryKey": [
                    "country"
                ],
                "value": "country",
                "resources": [
                    "ddf--entities--geo--country"
                ]
            },
```
https://github.com/Gapminder/ddf--pcbs--census/blob/d5815978a62465baa0ca916a5bef10bfa0856c85/datapackage.json#L5773-L5781

**Comment by jheeffer** [comment]
Thinking about it more now... we could also allow it, but it would make things more complicated. We'd need to have a good reason to do so.

One is the Singapore case. Singapore is both a city and a country. Cities can have `country` properties, describing what country they belong to. For consistency you might want Singapore to also have a `country` property (as it is a `city`). But that means that a `country` entity has a `country` property.

**Comment by jheeffer** [comment]
Side notes:

1. You cannot infer existence of this case from the file headers, since a `country` entity might be in a `geo` column (but have `is--country:true` somewhere to put it in `country` set).
2. Even if not allowed, this does not mean you cannot have a file containing `country` entities and a `country` property column. However, that column should be empty for the fields of the `country` entity rows.
E.g. the following would be valid.

| geo | name           | country | is--country |
| ------------- | ------------- | ----- | ---- |
| swe     | Sweden | | true |
| sto      | Stockholm      | swe | false |

But this file would be invalid (even though the `country` field contains the same value as the `geo` field). It defines a `country` entity property on `country` entity.

https://github.com/Gapminder/ddf--pcbs--census/blob/d5815978a62465baa0ca916a5bef10bfa0856c85/ddf--entities--geo--country.csv

**Comment by semio** [comment]
I agree that allowing entity property and entity key be same one make things complicated. In my opinion, we should not allow any duplicated columns in a data table. Also, if we allowed it, I don't think there are cases when the property value is not the same as its key, right? Such case sounds like it says 1 = 2 to me...

**Comment by semio** [comment]
Let's try to forbid such case and see what problem will it have:

```
Rule 1. Entity member in any domain(set) can't have entity property 
which name is same as the domain(set) name (except when property value is null)
```

And based on the [DDF data model document](https://docs.google.com/document/d/1Cd2kEH5w3SRJYaDcu-M4dU5SY8No84T3g-QlNSW6pIE/edit?disco=AAAAAfozv9s) , we can have an other rule to check what is allowed:

```
Rule 2. Entity member in a entity set of a domain can't have property 
which name is in the same domain but not in the drill_up list of that entity set. (except when property value is null)
```

So in the `sgp` case, this is allowed:

| city | name | country | is--city | is--country |
| -- | -- | -- | -- | -- |
| sgp | Singapore | sgp | True | True

and this one is not allowed:

| country | name | country | is--city | is--country |
| -- | -- | -- | -- | -- |
| sgp | Singapore | sgp | True | True

the query `select: { key: ["country"], value: ["country"] }` could be still valid, but it is only repeating the primaryKey column (always tautology).

**Comment by jheeffer** [comment]
Alright, if we disallow it we should completely disallow it. Even though it seems a tautology it is not. Key and value are two separate parts from a key-value pair with different semantics.
The key identifies an entity we describe. The value describes a property of an entity. 

So the following table says that the entity `sgp` has an property `country` with value `sgp`. A property says something about an entity. That distinction is important. `country` is not a great property name, but it works in most cases. Maybe better would `located_in_country` 

| geo | country |
| --- | --- |
| sgp | sgp | 

Think of this case where we have an entity domain `person` with entity set `father`. 

| person | father |
| --- | --- |
| x | y |
| y | z | 

In this case we also have the following key-value pairs (not seemingly tautologies)

| father | father |
| x | y | 
| y | z |

So if we disallow key-value pairs with identical concepts, we should not allow them anywhere. The only thing we can allow is if the value is empty which means in DDFcsv that the key-value pair does not exist. It occurs in cases where other entities in the table do have values for that property. For example:

| geo | name           | country | is--country |
| ------------- | ------------- | ----- | ---- |
| swe     | Sweden | | true |
| sto      | Stockholm      | swe | false |

**Comment by jheeffer** [comment]
A solution to still define the relation between the city of singapore and the country of singapore is with a `role`. I'll come back to that later. Basically it is an alias for an entity domain or set which will NEVER change to a different concept.

**Comment by jheeffer** [comment]
@buchslava please implement a new rule in validation to check for existence of key-value pairs where key is or contains the same concept as value.
One way to spot them is in datapackage.json:
```
            {
                "primaryKey": [
                    "country"
                ],
                "value": "country",
                "resources": [
                    "ddf--entities--geo"
                ]
            },
```
or
```
            {
                "primaryKey": [
                    "country",
                    "year"
                ],
                "value": "country",
                "resources": [
                    "ddf--datapoints--country--by--geo--year"
                ]
            },
```

**Comment by buchslava** [comment]
@jheeffer tell me please are concepts in this rule entities (domain and set)? (as far as I understand - we should check entities) what about roles?

**Comment by buchslava** [comment]
already resolved: see SAME_KEY_VALUE_CONCEPT rule details
