### ISSUE TITLE
implement new rule: inconsistent datapackage

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#475]
* **Rule name:** `INCONSISTENT_DATAPACKAGE`

* **Rule description:** 

datapackage complex checking for different inconsistence cases detection:
1. `resources` section should NOT be empty
2. for each of the resources:
 - path, name and schema should be defined
 - schema.primaryKey should be string or array of strings
 - schema.fields should be an array and its length should be >= 1
 - each of the fields should have `name` key
3. `ddfSchema` section should NOT be empty (`concepts` or `entities` or `datapoints` should be present)
4. for each of `ddfSchema`:
 - primaryKey should be an array of strings
 - value should be a string
 - resources should be an array of strings
5. 
  - extract uniquely `resources` from ddfSchema
  - extract uniquely names from each of member of `resources` section
  - their intersection should be empty: so, unused (between resources and ddfSchema) resource is a mistake

**Comment by jheeffer** [comment]
For this it might be more interesting to make a [json schema](http://json-schema.org/) file and test against that. I believe Semio had this at some point already but it might not be up to date.
Frictionless data also has json schemas for general datapackages (a valid ddf datapackage is a valid tabular datapackage but not necessarily the other way around).
http://frictionlessdata.io/specs/tabular-data-package/#meta

**Comment by semio** [comment]
I had a [json schema for recipe files](https://github.com/semio/ddf_utils/blob/master/res/specs/recipe.json) (and indeed it's outdated :)) I think point 1~4 can be checked with schema

**Comment by buchslava** [comment]
by the way, I can try to integrate https://github.com/frictionlessdata/datapackage-js for basic validation. But I guess I should provide some extra functionality (N5 in my description)

**Comment by jheeffer** [comment]
Great, yes. I think it's good to use frictionless data's own library too. That way we can more easily keep up with changing standards of datapackage.json.
So we have two validation steps
1. Is it a valid datapackage?
2. Is it a valid DDFcsv datapackage?

Step 1 you can use the library for
Step 2 is step 1 + extra checks according to DDFcsv datapackage specs
DDFcsv datapackage [specs](https://docs.google.com/document/d/10yzpTirAe-sAeMoCRzmMiCde1fEAtzMR6zfRY5E-fQs/edit) applied to our own json schema

@semio ah yes, it was for recipes, not datapackage.json, thanks!

**Comment by jheeffer** [comment]
So, before implementation we need two things:
1. Check current datapackage.json specs, see if our DDFcsv datapackage is still valid tabular datapackage
2. Create json schema for DDFcsv datapackage. Hopefully we can make it so we can make schema just for what is different from tabular datapackage?

@buchslava can you do these or should I help with 1 or 2?

**Comment by buchslava** [comment]
@jheeffer yes I need help

my questions are:
1. what does mean tabular datapackage? Is it all of datapackage.json or its particular part?
2. why should we create ddfSchema section if the section is present in datapackage? If we need to compare an existing datapackage with actual (just created) we should:
- create new datapackage
- compare both of sections: resources and ddfSchema
but this case does not detect integrity checking: this case is regarding actual or not actual datapackage

cc @angieskazka
