### ISSUE TITLE
datapackage rules should be applied before all of the checks

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#478]
datapackage rules should be applied before all of the checks as a separate logic

**Comment by angieskazka** [comment]
@buchslava related: if no datapackage in root stop validation and print "Dataset has no package.json in root folder. Run this validator with -i to generate one"

**Comment by buchslava** [comment]
@angieskazka as for now, this logic is a little different:
if no datapackage then validator will create it dynamically and provide checking via 'default' datapackage
