### ISSUE TITLE
Duplicate datapoints entries when using domain?

### ISSUE THREAD

**Issue by lapidus** [Gapminder/ddf-validation#546]
The default behaviour of `ddf-validate -i` when employing entity_domain seems to be to generate this under datapoints:

```
"ddfSchema": {
    "datapoints": [
      {
        "primaryKey": [
          "country",
          "time"
        ],
        "value": "adults_with_hiv_percent_age_15_49",
        "resources": [
          "adults_with_hiv_percent_age_15_49--by--geo--time"
        ]
      },
      {
        "primaryKey": [
          "geo",
          "time"
        ],
        "value": "adults_with_hiv_percent_age_15_49",
        "resources": [
          "adults_with_hiv_percent_age_15_49--by--geo--time"
        ]
      }
    ],
```

To me it seems a little bit ambiguous as the resource `adults_with_hiv_percent_age_15_49--by--geo--time` doesn't contain the primaryKey `country`. Wouldn't it be better to just have the `geo, time` entry here to avoid duplication and potential errors? 

Thanks!

**Comment by jheeffer** [comment]
Good question!

It's not a bug, it's a feature ;). The schema tells you for what keys certain values are available. 

1. It helps readers be efficient 
Think of a reader with only the info you propose getting the query:

```
select: { 
  key: ["country","time"], 
  value: ["adults_with_hiv_percent_age_15_49"] 
}
```

How would the reader know what file to check? ["geo","time"] is too broad, the dataset might just have data on `city` (also in `geo`) and not `country` for that indicator. Means the reader has to do a lot more work: reading all the geo (=city) data to then find out it doesn't contain any country data.

2. It helps populating UI.
Say a visualization is configured to only show countries over time. Should the indicator `adults_with_hiv_percent_age_15_49` be shown in a indicator dropdown for an encoding (e.g. axis, size)? If we just knew `geo,time` was available we wouldn't know if there's data for countries. The user might select it and then find out there was no data.
