### ISSUE TITLE
Space in ddf--concepts.csv silently breaks creation of datpackage.json

### ISSUE THREAD

**Issue by johnniehard** [Gapminder/ddf-validation#547]
Version 1.19.0

I've had an issure where a space after a comma in `ddf--concepts.csv` silently breaks creation of the `datapackage.json`.

With this in `ddf--concepts.csv`:

```
[...]
unemployed_aged_20_64, "Number of unemployed, female",measure,,employment,,,
[...]
```

the `ddfSchema` object is not created in `datapackage.json`. No errors reported. Validation file says everything went well.

This:
```
[...]
unemployed_aged_20_64,"Number of unemployed, female",measure,,employment,,,
[...]
```
works just fine.

It would be nice if having a space was not a problem, or the tool halted with a helpful error message.

**Comment by angiehjort** [comment]
@johnniehard this is fixed now in ddf-validation@1.19.3
please retest and reopen if persists
