### ISSUE TITLE
validation was finished with issues but the log is empty

### ISSUE THREAD

**Issue by semio** [Gapminder/ddf-validation#553]
ddf-validation version: 1.19.3
node version: 11.11.0

dataset: https://github.com/open-numbers/ddf--bp--energy master branch

Running validation-ddf against this dataset will show `Validation was finished with issues. Details are here: validation-xxx.log`, but the log file is an empty file.

**Comment by buchslava** [comment]
@semio I tested 1.19.3 on linux under 11.11.0
apart from that, I tested 1.19.3 under windows and I got exactly the same result

In my mind, ddf-validation works well

![Screenshot from 2019-04-01 10-33-28](https://user-images.githubusercontent.com/6974213/55311727-5aea0c80-546c-11e9-8e99-c19c4f3230f0.png)
![Screenshot from 2019-04-01 10-42-43](https://user-images.githubusercontent.com/6974213/55311733-5cb3d000-546c-11e9-8853-cbb6606df1d0.png)
![Screenshot from 2019-04-01 10-43-08](https://user-images.githubusercontent.com/6974213/55311736-5faec080-546c-11e9-8ce1-0fbfa9a9c923.png)

**Comment by semio** [comment]
I have this issue on macOS.. I tested in Linux and it worked indeed. So this issue should be OS specific issue.

```
semio at MacBook-Pro in ~/s/w/G/d/o/ddf--bp--energy on master [✓↩]
↪ validate-ddf
datapoints validation 100%[=========================================================================================================================================>]
Validation was finished with issues. Details are here: validation-2019-04-01T082736.283Z.log.
semio at MacBook-Pro in ~/s/w/G/d/o/ddf--bp--energy on master [✓↩]
↪ cat validation-2019-04-01T082736.283Z.log
semio at MacBook-Pro in ~/s/w/G/d/o/ddf--bp--energy on master [✓↩]
↪
```

I tried using `--silent` mode and it can print the result successfully. Do you have suggestions on how could I check what problem it is?

**Comment by angiehjort** [comment]
i retested on Mac OS El Capitan and it worked

![image](https://user-images.githubusercontent.com/3648190/55322066-8c1e0900-547b-11e9-8cc9-0ca147089ffb.png)

**Comment by semio** [comment]
Thanks @angieskazka. I tried installing node@8/ddf_validation@1.18 but none of them worked, and then I restarted my computer and it began to work! Should be a problem in my system and restarting fixed it. We can close this issue now.
