### ISSUE TITLE
NON_CONCEPT_HEADER rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#56]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule providing. This name should be a valid JS variable name and should be used for connecting with code.

`NON_CONCEPT_HEADER`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/non-concept-header`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

Each part of any header should be concept (is-- fields are excluded in this case)

* **Examples of correct data:**

ddf--concepts.csv
```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
country,entity_set,geo,Country
pop,measure,geo,Population
year,time,,year
```

ddf--datapoints--pop--by--country--year.csv
```
country,year,pop
vat,1960,100000
```

* **Examples of incorrect data:**

ddf--concepts.csv
```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
country,entity_set,geo,Country
pop,measure,geo,Population
year,time,,year
```

ddf--datapoints--pop--by--country--year.csv
```
countryFOO,year,pop
vat,1960,100000
```

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  one issue should be found for this rule
  output data for the issue should be expected
```

* **Output data format** Should be filled if type of Request is `rule`.

Should be included next information:

incorrect header value

**Comment by jheeffer** [comment]
Apart from is-- fields being excluded the following are also excluded:

`concept`, `concept_type`, `domain`

I think that's it for now.

**Comment by buchslava** [comment]
@jheeffer yes, but this rule is about datapoints checking (we will not touch concept file in this case)

**Comment by jheeffer** [comment]
right okay, good : )!

**Comment by buchslava** [comment]
Also needed extra functionality that I lost at the start of describing of the issue. We also need to check headers in concept file (excludes: `concept` and `concept_type`)
