### ISSUE TITLE
CONCEPT_MANDATORY_FIELD_NOT_FOUND rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#57]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule providing. This name should be a valid JS variable name and should be used for connecting with code.

`CONCEPT_MANDATORY_FIELD_NOT_FOUND`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/concept-mandatory-field-not-found`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

Mandatory fields for ALL concepts are not defined

* **Examples of correct data:**

`ddf--concepts.csv`
```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

* **Examples of incorrect data:**

`ddf--concepts.csv`
```
concept,domain,name
name,,
geo,,
country,geo,Country
pop,geo,Population
year,,year
```
`concept_type` field is missing in this case

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  one issue should be found for this rule
  output data for the issue should be expected
```
* **Output data format** Should be filled if type of Request is `rule`.

Should be included next information:

missing header values

* **Detailed Description** The more detailed the description, the easier it is for us to help.

expected mandatory header values are next: `concept` and `concept_type`

**Comment by buchslava** [comment]
@jheeffer tell me please, is `domain` header mandatory?

**Comment by jheeffer** [comment]
I saw you posted before (think you deleted it) to ask if domain is mandatory. Just to be sure: it is not strictly.
However, for entity sets and roles a domain is mandatory.
So a concept which has `concept_type` `entity_set` or `role`, `domain` is mandatory.
For `measure` it is optional.
