### ISSUE TITLE
WRONG_FILENAME rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#63]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`WRONG_FILENAME`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/wrong-filename`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

Current filename is NOT DDF. More info: https://docs.google.com/document/d/1aynARjsrSgOKsO1dEqboTqANRD1O9u7J_xmxy8m5jW8/edit#heading=h.1nakjy92hz6r
- **Examples of correct data:**

`ddf--concepts.csv`
`ddf--index.csv`
`ddf--entities--get--country.csv`
`ddf--datapoints--sg_population--by--geo--time.csv`
- **Examples of incorrect data:**

`foo.csv`
`df--entities--get--country.csv`
`ddf-entities-get-country.csv`
`ddf--index.csv.backup`
`ddf--datapoints--sg_population--by--geo--time`
- **Scenarios** Should be filled if type of Request is `rule`.

```
when files in dataset are correct
  any issue should NOT be found for this rule
```

```
when files in dataset are NOT correct
  one issue should be found for this rule
  output data for the issue should be expected
```
- **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

wrong filename

**Comment by jheeffer** [comment]
Only indexless datasets have filename restrictions.
Index does have to ALWAYS be ddf--index.csv though.
