### ISSUE TITLE
FILENAME_DOES_NOT_MATCH_HEADER rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#64]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`FILENAME_DOES_NOT_MATCH_HEADER`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/filename-does-not-match-header`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when headers (first line of csv) does not match to name of file. You can get more details here: https://docs.google.com/document/d/1aynARjsrSgOKsO1dEqboTqANRD1O9u7J_xmxy8m5jW8/edit#heading=h.1nakjy92hz6r

* **Examples of correct data:**

`ddf--entities--geo--country.csv` should include `country` in own header
`ddf--datapoints--sg_ini--by--geo--time.csv` should include `geo, time, sg_ini` in own header

* **Examples of incorrect data:**

`ddf--entities--geo--country.csv` contains `geo` or `foo`
`ddf--datapoints--sg_ini--by--geo--time.csv` contains `geo, time`
`ddf--datapoints--sg_ini--by--geo--time.csv` contains `foo`

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with wrong files quantity should be detected for this rule
  output data for any issue should be expected
```

* **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

filename and header

* **Detailed Description** The more detailed the description, the easier it is for us to help.

This rule should be implemented only for `entities` and `datapoints`

**Comment by jheeffer** [comment]
Just to be sure: This is only the case for indexless datasets.

`ddf--entities--geo--country.csv contains geo or foo`
`ddf--entities--geo--country.csv` may contain `geo`. That's valid.

**Comment by buchslava** [comment]
@jheeffer one little question

for example, we have an indexless DDF dataset

and:

`ddf--entities--geo--global.csv`
```
geo,is--global,name
world,TRUE,World
rus,FALSE,Russia
```

is this example invalid?

**Comment by jheeffer** [comment]
Good question

does `--global` infer is--global: true or just you can find is--global defined in here.

I'd say the first makes more sense.

So it would be invalid indeed.

**Comment by buchslava** [comment]
@jheeffer thats why I say that next case is wrong:

`ddf--entities--geo--country.csv contains geo or foo`

because 

`ddf--entities--geo--country.csv` should contain `country`

**Comment by jheeffer** [comment]
it does have to contain country, it can contain geo too as key instead of country, but every geo entity should have is--country: true.

**Comment by buchslava** [comment]
aha, ok, thanks
