### ISSUE TITLE
CONCEPT_NOT_USED rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#65]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`CONCEPT_NOT_USED`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/concept-not-used`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when concept that described in `ddf--concepts.csv` is not used in entities and datapoints.
- **Examples of correct data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

and

`ddf--entities--geo--country.csv`

```
country,gwid,name
afg,i0,Afghanistan
```
- **Examples of incorrect data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

only...
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  one issue should be found for this rule
  output data for the issue should be expected
```
- **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

array of NON used concepts
- **Detailed Description** The more detailed the description, the easier it is for us to help.

Now this rule should be implemented only for local (non distributed) DDF dataset.

**Comment by jheeffer** [comment]
Not an error. It is perfectly fine for a dataset to consist of only concepts, without entities or datapoints.

However, I do see the use of this in tool to clean up datasets.

**Comment by buchslava** [comment]
@jheeffer let it be warning

**Comment by jheeffer** [comment]
Hmm, no not even. There will be datasets like this and they shouldn't give warnings.

Maybe a different tool or a mode of validation ('--cleanup' or something) at a later time, but not for standard validation.

**Comment by buchslava** [comment]
@jheeffer ok, sure
