### ISSUE TITLE
EMPTY_DATA rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#66]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`EMPTY_DATA`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/empty-data`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when file with true name and header does not contain any data under the header.

* **Examples of correct data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

* **Examples of incorrect data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
```

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  one issue should be found for this rule
  output data for the issue should be expected
```

* **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

filename and header

* **Detailed Description** The more detailed the description, the easier it is for us to help.

This issue should be warning.

**Comment by jheeffer** [comment]
This should be a warning right?

**Comment by buchslava** [comment]
@jheeffer yes, sure
