### ISSUE TITLE
UNEXPECTED_DATA rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#67]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`UNEXPECTED_DATA`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/unexpected-data`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when filename and header are good but content isn't: content 

* **Examples of correct data:**

```
ddf--concepts.csv

concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

* **Examples of incorrect data:**

```
ddf--concepts.csv

concept,concept_type,domain,name
foo
geo,entity_domain,,
```

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with wrong lines (records) quantity should be detected for this rule
  output data for any issue should be expected
```

* **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

content of line or incorrect record

* **Detailed Description** The more detailed the description, the easier it is for us to help.

next refactoring should be expected: create common library with `rules functions` for cross rule using!

**Comment by jheeffer** [comment]
This is more test for invalid csv, no? You could use csvlint for this maybe?
https://libraries.io/npm/csvlint

**Comment by buchslava** [comment]
@jheeffer sure, I'll apply it, tnx
