### ISSUE TITLE
INDEX_NOT_FULL rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#69]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`INDEX_NOT_FULL`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/index-not-full`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when DDF dataset contains valid DDF files that not included in `ddf--index.csv`

* **Examples of correct data:**

`ddf--index.csv`
```
key,value,file
concept,name,ddf--concepts.csv
```
and

`ddf--concepts.csv` file exists

* **Examples of incorrect data:**

`ddf--index.csv`
```
key,value,file
concept,name,ddf--concepts.csv
```
and
DDF dataset has `ddf--datapoints--aid_given_per_person_2007_us--by--geo--time.csv` file

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with expected files should be detected for this rule
  output data for any issue should be expected
```

* **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

expected filename

**Comment by jheeffer** [comment]
I guess this is: index file does not exist?

**Comment by buchslava** [comment]
not actual in accordance with #156
