### ISSUE TITLE
DATAPOINTS_NOT_FOUND rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#72]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`DATAPOINTS_NOT_FOUND`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/datapoints-not-found`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when datapoints will not be detected for current DDF dataset.
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when datapoints are not present
  one issue (warning) should be found for this rule
  output data for the issue should be expected
```

**Comment by jheeffer** [comment]
A dataset without datapoints is not invalid.
