### ISSUE TITLE
CONCEPTS_NOT_FOUND rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#73]
* **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`CONCEPTS_NOT_FOUND`

* **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/concepts-not-found`

* **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when concepts will not be detected for current DDF dataset.

* **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when concepts are not present
  one issue (warning) should be found for this rule
  output data for the issue should be expected
```

**Comment by jheeffer** [comment]
Yes, every dataset should have a concepts table.

Though we did discuss this before. Maybe it's possible to have a concepts-less dataset with just datapoints. For now, let's keep concepts mandatory.
