### ISSUE TITLE
ENTITIES_NOT_FOUND rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#74]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`ENTITIES_NOT_FOUND`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/entities-not-found`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when entities will not be detected for current DDF dataset.
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when entities are not present
  one issue (warning) should be found for this rule
  output data for the issue should be expected
```

**Comment by jheeffer** [comment]
Not sure what invalidity this is about?

It's perfectly possible to have a dataset without entities.
