### ISSUE TITLE
INVALID_CONCEPT_TYPE rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#75]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`INVALID_CONCEPT_TYPE`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/invalid-concept-type`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when type of current concept is not from next list:

entity_set, entity_domain, string, measure, time
- **Examples of correct data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```
- **Examples of incorrect data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,foo,,
```
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with wrong concept types quantity should be detected for this rule
  output data for any issue should be expected
```
- **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

wrong concept type

**Comment by jheeffer** [comment]
According to 

https://docs.google.com/document/d/1Cd2kEH5w3SRJYaDcu-M4dU5SY8No84T3g-QlNSW6pIE/edit#heading=h.grzrcc4znf3e

there are is no invalid concept_type.

measure, string, time, interval, entity_set, entity_domain, role, composite are built in and have special meaning within DDF.

So this would be valid:

```
concept, concept_type, name
borders, geojson,      "Borders of the country"
```
```
country, name,    borders
swe,     Sweden, '{"type": "Feature","geometry": {"type": "Point","coordinates": [125.6, 10.1]},"properties": {"name": "Dinagat Islands"}}'
```
Is this creating big problems? Not sure, should we be more strict?

It's useful so people can add 'types' themselves for particular datasets that contain certain types of data we don't support.
