### ISSUE TITLE
INVALID_CONCEPT_DOMAIN rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#76]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`INVALID_CONCEPT_DOMAIN`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/invalid-concept-domain`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when `domain` in concept is defined and not valid (has type different from `entity_domain`)
- **Examples of correct data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```
- **Examples of incorrect data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with wrong concept domains quantity should be detected for this rule
  output data for any issue should be expected
```
- **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

concept record
invalid domain

**Comment by jheeffer** [comment]
Also:
When 
concept_type is `entity_set`, domain should be an entity_domain
concept_type is `role`, domain should be an entity_domain or entity_set
concept_type is `measure`, domain may be a string (maybe later just JSON string)
concept_type is anything else domain should be empty

**Comment by buchslava** [comment]
duplicated: https://github.com/Gapminder/ddf-validation/issues/57
