### ISSUE TITLE
WRONG_ENTITY_IS_HEADER rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#82]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`WRONG_ENTITY_IS_HEADER`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/wrong-entity-is-header`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when `is-header` in concept is defined and not valid: not a  concept with `entity_set` type
- **Examples of correct data:**

`ddf--concepts.csv`

```
"concept","name","concept_type","domain",
"income_groups","Income groups","entity_set","geo",
"geo","Geographic location","entity_domain",,
```

and
`ddf--entities--geo--income_groups.csv`

```
income_groups,name,gwid,is--income_groups
high_income,High income,i268,TRUE
lower_middle_income,Lower middle income,i269,TRUE
low_income,Low income,i266,TRUE
upper_middle_income,Upper middle income,i267,TRUE
```
- **Examples of incorrect data:**

`ddf--concepts.csv`

```
"concept","name","concept_type","domain",
"income_groups","Income groups","entity_set","geo",
"geo","Geographic location","entity_domain",,
```

and
`ddf--entities--geo--income_groups.csv`

```
income_groups,name,gwid,is--foo_groups
high_income,High income,i268,TRUE
lower_middle_income,Lower middle income,i269,TRUE
low_income,Low income,i266,TRUE
upper_middle_income,Upper middle income,i267,TRUE
```
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with wrong is-headers quantity should be detected for this rule
  output data for any issue should be expected
```
- **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

file, wrong header

**Comment by jheeffer** [comment]
To be clear:

is--header is not mandatory anywhere, absence just means all entities have value false for that is--header.

only error when: `is--xxx` is used when `xxx` is not defined in concepts. No other case should give an error.

So the following is also valid (though the `is--country` is nonsensical):
`ddf--concepts.csv`
```
"concept","name","concept_type","domain",
"income_groups","Income groups","entity_set","geo",
"geo","Geographic location","entity_domain",,
"country","Country","entity_set","geo"
```
`incomegroups.csv`
```
income_groups,name,gwid,is--income_groups,is--country
high_income,High income,i268,TRUE,FALSE
lower_middle_income,Lower middle income,i269,TRUE,FALSE
low_income,Low income,i266,TRUE,TRUE
upper_middle_income,Upper middle income,i267,TRUE,TRUE
```
`ddf--index.csv`
```
"key","value","file"
"income_groups","name","incomegroups.csv"
"income_groups","gwid","incomegroups.csv"
```
