### ISSUE TITLE
ENTITY_FILE_NOT_FOUND rule providing

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#84]
- **Rule name:** Should be filled if this issue depends on particular rule especially during new rule creation. This name should be a valid JS variable name and should be used for connecting with code.

`ENTITY_FILE_NOT_FOUND`
- **Rule test folder:** Should be filled if type of Request is `rule`. Needed for documentation auto generation. 

`test/fixtures/rules-cases/entity-file-not-found`
- **Rule description:** Should be filled if type of Request is `rule`. Needed for documentation auto generation.

An issue according to this rule will be fired when file that related with entity set/domain in `ddf--concepts.csv` is not found.
- **Examples of correct data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

and 

`ddf--entities--geo--country.csv` file is exist
- **Examples of incorrect data:**

`ddf--concepts.csv`

```
concept,concept_type,domain,name
name,string,,
geo,entity_domain,,
region,entity_set,geo,Region
country,entity_set,geo,Country
capital,entity_set,geo,Capital
pop,measure,geo,Population
year,time,,year
```

and 

`ddf--entities--geo--country.csv` file does not exists
- **Scenarios** Should be filled if type of Request is `rule`.

```
when dataset is correct
  any issue should NOT be found for this rule
```

```
when dataset is NOT correct
  issues in accordance with missing entity files quantity should be detected for this rule
  output data for any issue should be expected
```
- **Output data format** Additional data that depends on particular issue type. Should be filled if type of Request is `rule`.

concept (entity set/entity domain) name

**Comment by jheeffer** [comment]
This is not an error or warning.

A concept can exist without actual data for that concept.

For example, we can make 'ontology' datasets which define concepts we use in gapminder. They don't contain any data (i.e. entities/datapoints). They only define the concepts: names, types, descriptions etc.
These ontologies are then used to merge with other datasets containing real data. That data is then fitted to the gapminder concepts in the ontology.
https://en.wikipedia.org/wiki/Ontology_(information_science)
