### ISSUE TITLE
MEASURE_VALUE_NOT_NUMERIC using

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#86]
I think this rule should be warning.

**Comment by buchslava** [comment]
@jheeffer what do you think?

**Comment by jheeffer** [comment]
data point values do not have to be numeric. they can be non-numeric too.

See the government_type values here:
https://docs.google.com/document/d/1Cd2kEH5w3SRJYaDcu-M4dU5SY8No84T3g-QlNSW6pIE/edit#heading=h.h9x68on4mvz0

**Comment by buchslava** [comment]
not actual

**Comment by jheeffer** [comment]
Measures should be numeric.
